name: CI

on:
  push:
    branches:
      - main  # Adjust if needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push springboot-app image
        working-directory: ./fourscape
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/springboot-app:latest .
          docker push ghcr.io/${{ github.repository_owner }}/springboot-app:latest
